# Generated by Django 4.0.1 on 2022-10-27 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goalpoolapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='leaguecode',
            field=models.CharField(blank=True, editable=False, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='league',
            name='leaguename',
            field=models.CharField(default='Default', max_length=64),
            preserve_default=False,
        ),
    ]
