# Generated by Django 4.0.1 on 2022-10-27 14:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goalpoolapp', '0002_league_leaguecode_league_leaguename'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='admin',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='administratedleague', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='league',
            name='draftComplete',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='league',
            name='draftStarted',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='league',
            name='duplicatePlayersAllowed',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='league',
            name='transfersActivated',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
