# Generated by Django 4.0.1 on 2022-10-27 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goalpoolapp', '0003_league_admin_league_draftcomplete_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='draftComplete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='league',
            name='draftStarted',
            field=models.BooleanField(default=False),
        ),
    ]
