# Generated by Django 4.0.1 on 2022-10-27 15:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goalpoolapp', '0004_alter_league_draftcomplete_alter_league_draftstarted'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='teamplayerslimit',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(20), django.core.validators.MinValueValidator(1)]),
            preserve_default=False,
        ),
    ]
