# Generated by Django 4.0.1 on 2022-10-28 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goalpoolapp', '0005_league_teamplayerslimit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='leaguecode',
            field=models.CharField(default='default', max_length=10),
            preserve_default=False,
        ),
    ]
