# Generated by Django 4.0.1 on 2022-10-28 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goalpoolapp', '0006_alter_league_leaguecode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='leaguecode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
