# Generated by Django 4.0.1 on 2022-10-28 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goalpoolapp', '0007_alter_league_leaguecode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='name',
            new_name='teamname',
        ),
    ]
