# Generated by Django 4.0.1 on 2022-10-31 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goalpoolapp', '0008_rename_name_team_teamname'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='draftPosition',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='draftNumber',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
