# Generated by Django 4.0.1 on 2022-10-31 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goalpoolapp', '0010_alter_team_draftnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='totalgoals',
            field=models.IntegerField(default=0),
        ),
    ]
