# Generated by Django 4.0.1 on 2022-10-31 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goalpoolapp', '0011_team_totalgoals'),
    ]

    operations = [
        migrations.RenameField(
            model_name='league',
            old_name='draftComplete',
            new_name='draftcomplete',
        ),
        migrations.RenameField(
            model_name='league',
            old_name='draftPosition',
            new_name='draftposition',
        ),
        migrations.RenameField(
            model_name='league',
            old_name='draftStarted',
            new_name='draftstarted',
        ),
    ]
