# Generated by Django 4.0.1 on 2022-10-31 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goalpoolapp', '0012_rename_draftcomplete_league_draftcomplete_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='draftNumber',
            new_name='draftnumber',
        ),
    ]
