# Generated by Django 4.0.1 on 2022-10-31 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goalpoolapp', '0013_rename_draftnumber_team_draftnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='draftposition',
            field=models.IntegerField(default=1),
        ),
    ]
