# Generated by Django 4.0.1 on 2022-10-31 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goalpoolapp', '0014_alter_league_draftposition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='leagues',
            field=models.ManyToManyField(related_name='leagueplayers', to='goalpoolapp.League'),
        ),
    ]
