# Generated by Django 4.0.1 on 2022-10-31 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goalpoolapp', '0015_alter_player_leagues'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='draftdecending',
            field=models.BooleanField(default=False),
        ),
    ]
