# Generated by Django 4.0.1 on 2022-11-01 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goalpoolapp', '0017_rename_name_player_nickname_player_firstname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='playercode',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
