# Generated by Django 4.0.1 on 2022-11-03 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goalpoolapp', '0018_player_playercode'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='transfersAllowed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='team',
            name='provisionalplayers',
            field=models.ManyToManyField(blank=True, related_name='provisionalteams', to='goalpoolapp.Player'),
        ),
        migrations.AlterField(
            model_name='league',
            name='transfersActivated',
            field=models.BooleanField(default=False),
        ),
    ]
