# Generated by Django 4.0.1 on 2022-11-05 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goalpoolapp', '0019_league_transfersallowed_team_provisionalplayers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fixture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
                ('round', models.IntegerField()),
                ('hometeam', models.CharField(max_length=20)),
                ('awayteam', models.CharField(max_length=20)),
                ('homescore', models.IntegerField(default=0)),
                ('awayscore', models.IntegerField(default=0)),
            ],
        ),
    ]
