# Generated by Django 4.0.1 on 2022-11-05 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goalpoolapp', '0020_fixture'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixture',
            name='date',
            field=models.DateTimeField(default='2023-05-28T15:00:00Z'),
            preserve_default=False,
        ),
    ]
