# Generated by Django 4.0.1 on 2022-11-05 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goalpoolapp', '0021_fixture_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='roundnumber',
            field=models.IntegerField(default=17),
            preserve_default=False,
        ),
    ]
