# Generated by Django 4.0.1 on 2022-11-05 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goalpoolapp', '0023_fixture_awayscorers_fixture_homescorers'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='currentweekgoals',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
