# Generated by Django 4.0.1 on 2022-11-07 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goalpoolapp', '0024_player_currentweekgoals'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalVars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roundnumber', models.IntegerField(default=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='league',
            name='roundnumber',
        ),
    ]
