# Generated by Django 4.0.1 on 2022-11-10 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goalpoolapp', '0026_team_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='teamplayerslimit',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='player',
            name='currentweekgoals',
            field=models.IntegerField(default=0),
        ),
    ]
