# Generated by Django 4.0.1 on 2022-11-13 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goalpoolapp', '0027_alter_league_teamplayerslimit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RealTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamname', models.CharField(max_length=20)),
                ('teampic', models.CharField(max_length=50)),
            ],
        ),
    ]
