# Generated by Django 4.0.1 on 2022-11-13 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goalpoolapp', '0028_realteam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='realteam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='goalpoolapp.realteam'),
        ),
    ]
