# Generated by Django 4.0.1 on 2022-11-13 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goalpoolapp', '0029_alter_player_realteam'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='pic',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='player',
            name='realteam',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='realteam',
            name='teampic',
            field=models.CharField(max_length=100),
        ),
    ]
