# Generated by Django 4.0.1 on 2022-11-13 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goalpoolapp', '0030_player_pic_alter_player_realteam_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='realteam',
            name='teamid',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
