# Generated by Django 4.0.1 on 2022-11-13 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goalpoolapp', '0032_alter_player_realteam'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RealTeam',
            new_name='Country',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='realteam',
            new_name='country',
        ),
    ]
