# Generated by Django 4.0.1 on 2022-11-13 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goalpoolapp', '0034_alter_player_goals'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='teamid',
            new_name='countryid',
        ),
        migrations.RenameField(
            model_name='country',
            old_name='teamname',
            new_name='countryname',
        ),
        migrations.RenameField(
            model_name='country',
            old_name='teampic',
            new_name='countrypic',
        ),
    ]
