# Generated by Django 4.0.1 on 2022-11-14 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goalpoolapp', '0036_alter_fixture_awayteam_alter_fixture_hometeam'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='permission',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
