# Generated by Django 4.0.1 on 2022-11-14 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goalpoolapp', '0037_user_permission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='leagues',
            field=models.ManyToManyField(blank=True, related_name='leagueplayers', to='goalpoolapp.League'),
        ),
    ]
