# Generated by Django 4.0.1 on 2022-11-15 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goalpoolapp', '0039_alter_player_goals'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixture',
            name='finished',
            field=models.BooleanField(default=False),
        ),
    ]
