# Generated by Django 4.0.1 on 2022-11-15 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goalpoolapp', '0040_fixture_finished'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='permission',
            new_name='emailpermission',
        ),
    ]
