# Generated by Django 4.0.1 on 2022-11-15 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goalpoolapp', '0041_rename_permission_user_emailpermission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='emailpermission',
            field=models.BooleanField(null=True),
        ),
    ]
