# Generated by Django 4.0.1 on 2022-11-16 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goalpoolapp', '0042_alter_user_emailpermission'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='position',
            field=models.CharField(default='all', max_length=12),
            preserve_default=False,
        ),
    ]
